# Generated by Django 4.2 on 2023-05-09 08:39

from django.db import migrations, models
import point_cloud_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('point_cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='file',
            field=models.FileField(upload_to='', validators=[point_cloud_app.validators.validate_is_las], verbose_name='Файл'),
        ),
    ]
